// <auto-generated />
namespace GameCore.WcfService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlternativeUnits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlternativeUnits));
        
        string IMigrationMetadata.Id
        {
            get { return "201607031411301_AlternativeUnits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
